"""Collect a complete client capture run into the public screenshot folders."""

from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parents[1]
GROUPS = (
    ("cabin-books-", "cabin/books", "Book installation"),
    ("crafting-room-", "cabin/crafting", "Cabin crafting stations"),
    ("cabin-exterior-", "cabin/exterior", "Cabin exterior"),
    ("greenhouse-", "cabin/greenhouse", "Greenhouse"),
    ("cabin-storage-", "cabin/storage", "Cabin storage"),
    ("cabin-upgrades-", "cabin/upgrades", "Cabin upgrades"),
    ("vanilla-creative-", "vanilla/creative-inventory", "Vanilla creative inventory"),
    ("vanilla-", "vanilla/crafting-stations", "Vanilla crafting stations"),
)


def collect(source: Path, destination: Path) -> int:
    groups = {folder: [] for _, folder, _ in GROUPS}
    for screenshot in sorted(source.glob("*.png")):
        for prefix, folder, _ in GROUPS:
            if screenshot.name.startswith(prefix):
                groups[folder].append(screenshot)
                break
        else:
            raise ValueError(f"Add a screenshot group for {screenshot.name}")

    missing = [folder for folder, files in groups.items() if not files]
    if missing:
        raise ValueError(f"Incomplete capture; missing groups: {', '.join(missing)}")

    index = [
        "# Screenshots",
        "",
        "Run `just screenshots` from the repository root to regenerate every capture.",
        "The command includes all cabin screens, exterior views, and vanilla references.",
        "It uses a graphical display, or Xvfb when no display is configured.",
        "",
        "Keep screenshots in these folders so their paths remain stable.",
        "Experiment notes link here. These captures are visual references;",
        "no regression baselines have been accepted.",
        "",
        "This index is generated by `scripts/collect-screenshots.py`.",
    ]
    count = 0
    for _, folder, title in GROUPS:
        target = destination / folder
        target.mkdir(parents=True, exist_ok=True)
        files = groups[folder]
        expected = {file.name for file in files}
        for file in files:
            shutil.copy2(file, target / file.name)
        for old in target.glob("*.png"):
            if old.name not in expected:
                old.unlink()
        index.extend(["", f"## {title}", ""])
        index.extend(f"- [{file.stem}]({folder}/{file.name})" for file in files)
        count += len(files)

    (destination / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    return count


if __name__ == "__main__":
    try:
        count = collect(ROOT / "build/run/clientGameTest/screenshots", ROOT / "screenshots")
    except ValueError as error:
        raise SystemExit(str(error))
    print(f"Saved {count} screenshots in screenshots/; browse screenshots/README.md")
